/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjektG2;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author lisajansson
 */
public class SkapaAnvandare extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form SkapaInlogg
     */
    public SkapaAnvandare(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        personnummer = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        fornamn = new javax.swing.JLabel();
        efternamn = new javax.swing.JLabel();
        beskrivning = new javax.swing.JLabel();
        kontorsrum = new javax.swing.JLabel();
        titel = new javax.swing.JLabel();
        tfPnr = new javax.swing.JTextField();
        tfTitel = new javax.swing.JTextField();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfRum = new javax.swing.JTextField();
        btnSkapa = new javax.swing.JButton();
        personnummer1 = new javax.swing.JLabel();
        tfMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfLosen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Menlo", 0, 36)); // NOI18N
        jLabel1.setText("Skapa ny användare");

        personnummer.setText("Personnummer");

        text1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        text1.setText("ÅÅÅÅMMDDXXXX");

        fornamn.setText("Förnamn");

        efternamn.setText("Efternamn");

        beskrivning.setText("Beskrivning");

        kontorsrum.setText("Kontorsrum");

        titel.setText("Titel");

        btnSkapa.setText("Skapa ny användare");
        btnSkapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaActionPerformed(evt);
            }
        });

        personnummer1.setText("Email");

        jLabel2.setText("Lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personnummer)
                    .addComponent(titel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(beskrivning)
                                .addComponent(efternamn)
                                .addComponent(fornamn)))
                        .addComponent(kontorsrum, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2)
                    .addComponent(personnummer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfFornamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPnr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEfternamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBeskrivning, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRum, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSkapa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tfMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLosen))
                        .addGap(161, 161, 161))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personnummer)
                    .addComponent(tfPnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titel)
                    .addComponent(tfTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornamn)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(efternamn)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(beskrivning)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kontorsrum)
                    .addComponent(tfRum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personnummer1)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSkapa)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaActionPerformed
        // Knapp lägg till en ny lärare i systemet

        //VARIABLAR FÖR LÄGGA TILL ANVÄNDARE
        String pnr = tfPnr.getText(); //Textbox personnummer, lokal variabel hämtar textfältet
        String titeln = tfTitel.getText();
        String fnamn = tfFornamn.getText();
        String enamn = tfEfternamn.getText();
        String beskrivning = tfBeskrivning.getText();
        String kontorsnr = tfRum.getText();
        String losenord = tfLosen.getText();
        String admin = "V"; //Sätter användare till icke admin by default
        String email = tfMail.getText();
        String notis = "F";

        //KOLLAR OM NÅGON RUTA ÄR TOM
        if (Validering.textFaltHarVarde(pnr) && Validering.textFaltHarVarde(titeln) && Validering.textFaltHarVarde(fnamn)
                && Validering.textFaltHarVarde(enamn) && Validering.textFaltHarVarde(beskrivning) && Validering.textFaltHarVarde(kontorsnr)
                && Validering.textFaltHarVarde(losenord) && Validering.textFaltHarVarde(email)) {

            //KOLLA OM NAMN ELLER EFTERNAMN ÄR I BOKSTÄVER
            if (Validering.vardeArString(tfFornamn) && Validering.vardeArString(tfEfternamn)) {

                //KOLLAR OM PERSONNR ÄR SIFFRA
                if (Validering.vardeArSiffra(tfPnr) && tfPnr.getText().length() == 12) {

                    //VARIABLAR FÖR EMAIL
                    String amne = "Nytt konto har skapats";
                    String valkommen = "Välkommen " + fnamn + " till lärarplattformen för Informatik! \n\n"
                            + "Ditt användarnamn är: " + pnr + " \n"
                            + "Ditt lösenord är: " + losenord;

                    try {

                        String fraga = "INSERT INTO anvandare(PNR, fornamn, efternamn, beskrivning, losenord, kontorsnr, titel, adminstatus) VALUES(" + pnr + ", '" + fnamn + "', '" + enamn + "', '" + beskrivning + "', '" + losenord + "', '" + kontorsnr + "', '" + titeln + "', '" + admin + "')";
                        idb.insert(fraga); // Uppdaterar databasen

                        String fraga2 = "INSERT INTO EMAIL(MAIL, NOTIS, PNR) VALUES('" + email + "', '" + notis + "', '" + pnr + "')";

                        JOptionPane.showMessageDialog(null, "Användaren har lagts till i systemet");
                        idb.insert(fraga2); // Uppdaterar databasen         

                        //KÖR METOD FÖR ATT SKICKA MAIL I KLASSEN START
                        Mail.start(email, amne, valkommen);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage()); // Pop up felmeddelande
                    }
                    // PERSONNUMMRET ÄR INTE 12 SIFFOR
                    } else {
                        JOptionPane.showMessageDialog(null, "Ditt personnummer måste vara 12 siffror.");
                }
                //OM FÖRNAMN ELLER EFTERNAMN ÄR ANNAT ÄN BOKSTÄVER
            } else {
                JOptionPane.showMessageDialog(null, "Är det där verkligen ditt namn?");
            }
            //OM NÅGOT FÄLT ÄR TOMT
        } else {
            JOptionPane.showMessageDialog(null, "Alla fält måste vara ifyllda.");
        }

    }//GEN-LAST:event_btnSkapaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beskrivning;
    private javax.swing.JButton btnSkapa;
    private javax.swing.JLabel efternamn;
    private javax.swing.JLabel fornamn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kontorsrum;
    private javax.swing.JLabel personnummer;
    private javax.swing.JLabel personnummer1;
    private javax.swing.JLabel text1;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfLosen;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfPnr;
    private javax.swing.JTextField tfRum;
    private javax.swing.JTextField tfTitel;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
